services:
  bgt-pwa:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_HEALTH_BASE_URL: ${VITE_API_HEALTH_BASE_URL}
        VITE_MOCK_API: ${VITE_MOCK_API}
        VITE_OIDC_CLIENT_ID: ${VITE_OIDC_CLIENT_ID}
        VITE_OIDC_REDIRECT_URI: ${VITE_OIDC_REDIRECT_URI}
        VITE_OIDC_SCOPE: ${VITE_OIDC_SCOPE}
        VITE_OIDC_AUTH_ENDPOINT: ${VITE_OIDC_AUTH_ENDPOINT}
        VITE_OIDC_TOKEN_ENDPOINT: ${VITE_OIDC_TOKEN_ENDPOINT}
        VITE_OIDC_AUDIENCE: ${VITE_OIDC_AUDIENCE} 
    environment:
      NGINX_API_UPSTREAM: ${NGINX_API_UPSTREAM}
      NGINX_API_HOST: ${NGINX_API_HOST}
      NGINX_AUTH_UPSTREAM: ${NGINX_AUTH_UPSTREAM}
    ports:
      - "3000:80"
    container_name: bgt-pwa