# -------- Build stage --------
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# -------- Runtime stage --------
FROM nginx:alpine

# Borra config default
RUN rm /etc/nginx/conf.d/default.conf

# Config simple para SPA
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia solo el build
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]