name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Configura el entorno de Node.js 
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm' 

    # Instala las dependencias del proyecto
    - name: Install Dependencies
      run: npm install

    # Corre el comando de tests que usas localmente
    - name: Run Unit and Integration Tests
      run: npm run test 

